# case 1
nilai1 = float(input("Masukan Nilai Pertama : "))
nilai2 = float(input("Masukan Nilai Kedua : "))
hasil1 = nilai1 + nilai2
print(f"Hasil dari penjumlahan nilai pertama \"{nilai1:.2f}\" dan nilai kedua\"{nilai2:.2f}\"adalah\"{hasil1:.2f}\"")
# case 2
Nilai1_2 = float(input("Masukan Nilai Pertama : "))
Nilai2_2 = float(input("Masukan Nilai Kedua : "))
hasil2 = Nilai1_2 + Nilai2_2
print(f"Hasil dari penjumlahan nilai pertama \"{Nilai1_2:.2f}\" dan nilai kedua \"{Nilai2_2:.2f}\" adalah \"{hasil2:.2f}\"")